"""Auto-generated

Revision ID: 6dd455063abe
Revises: b59d987c770b
Create Date: 2025-09-13 12:46:16.238906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dd455063abe'
down_revision = 'b59d987c770b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_pre_shared_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_truncated', sa.String(length=50), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.Enum('WORKSTATION', 'SERVER', 'GATEWAY', 'IOT_DEVICE', 'MOBILE', 'KIOSK', 'APPLIANCE', 'OTHER', name='devicetype'), nullable=False),
    sa.Column('device_serial', sa.String(length=255), nullable=True),
    sa.Column('device_mac_address', sa.String(length=17), nullable=True),
    sa.Column('certificate_type', sa.Enum('CLIENT', 'SERVER', 'BOTH', name='certificatetype'), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=True),
    sa.Column('subject_alt_names', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('assigned_ip_range', sa.String(length=18), nullable=True),
    sa.Column('dns_suffix', sa.String(length=255), nullable=True),
    sa.Column('template_set', sa.String(length=100), nullable=False),
    sa.Column('policy_group', sa.String(length=100), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('last_certificate_issued', sa.DateTime(timezone=True), nullable=True),
    sa.Column('certificate_serial', sa.String(length=255), nullable=True),
    sa.Column('provisioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_managed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified_by', sa.String(length=255), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_ip', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    with op.batch_alter_table('device_pre_shared_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_pre_shared_keys_device_mac_address'), ['device_mac_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_pre_shared_keys_device_name'), ['device_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_pre_shared_keys_device_serial'), ['device_serial'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_pre_shared_keys_key_truncated'), ['key_truncated'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_pre_shared_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_pre_shared_keys_key_truncated'))
        batch_op.drop_index(batch_op.f('ix_device_pre_shared_keys_device_serial'))
        batch_op.drop_index(batch_op.f('ix_device_pre_shared_keys_device_name'))
        batch_op.drop_index(batch_op.f('ix_device_pre_shared_keys_device_mac_address'))

    op.drop_table('device_pre_shared_keys')
    # ### end Alembic commands ###
