"""Add psk_type field to PreSharedKey for computer-identity PSKs

Revision ID: a4166104da13
Revises: 6dd455063abe
Create Date: 2025-09-14 17:45:58.394853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4166104da13'
down_revision = '6dd455063abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pre_shared_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('psk_type', sa.String(length=20), nullable=False, server_default='server'))
        batch_op.create_index(batch_op.f('ix_pre_shared_keys_psk_type'), ['psk_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pre_shared_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pre_shared_keys_psk_type'))
        batch_op.drop_column('psk_type')

    # ### end Alembic commands ###
