"""Auto-generated

Revision ID: b2bb7ff57799
Revises: 
Create Date: 2025-09-08 22:05:45.838190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2bb7ff57799'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('user', sa.String(length=255), nullable=False),
    sa.Column('cn', sa.String(length=255), nullable=True),
    sa.Column('requester_ip', sa.String(length=45), nullable=True),
    sa.Column('requester_user_agent', sa.Text(), nullable=True),
    sa.Column('cert_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent_string', sa.String(length=255), nullable=True),
    sa.Column('detected_os', sa.String(length=50), nullable=True),
    sa.Column('optionset_used', sa.String(length=255), nullable=True),
    sa.Column('ovpn_content', sa.LargeBinary(), nullable=True),
    sa.Column('downloadable', sa.Boolean(), nullable=False),
    sa.Column('collected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('download_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_download_tokens_cn'), ['cn'], unique=False)
        batch_op.create_index(batch_op.f('ix_download_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_download_tokens_user'), ['user'], unique=False)

    op.create_table('pre_shared_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('template_set', sa.String(length=100), nullable=False),
    sa.Column('key_truncated', sa.String(length=50), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    with op.batch_alter_table('pre_shared_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pre_shared_keys_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_pre_shared_keys_key_truncated'), ['key_truncated'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pre_shared_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pre_shared_keys_key_truncated'))
        batch_op.drop_index(batch_op.f('ix_pre_shared_keys_description'))

    op.drop_table('pre_shared_keys')
    with op.batch_alter_table('download_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_download_tokens_user'))
        batch_op.drop_index(batch_op.f('ix_download_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_download_tokens_cn'))

    op.drop_table('download_tokens')
    # ### end Alembic commands ###
