"""Auto-generated

Revision ID: b59d987c770b
Revises: b2bb7ff57799
Create Date: 2025-09-12 23:08:30.180769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b59d987c770b'
down_revision = 'b2bb7ff57799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=False),
    sa.Column('certificate_type', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('request_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('raw_user_agent', sa.Text(), nullable=True),
    sa.Column('detected_os', sa.String(length=50), nullable=True),
    sa.Column('os_version', sa.String(length=50), nullable=True),
    sa.Column('browser', sa.String(length=50), nullable=True),
    sa.Column('browser_version', sa.String(length=50), nullable=True),
    sa.Column('is_mobile', sa.Boolean(), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=True),
    sa.Column('template_set', sa.String(length=100), nullable=True),
    sa.Column('signing_successful', sa.Boolean(), nullable=True),
    sa.Column('signing_error_message', sa.Text(), nullable=True),
    sa.Column('certificate_serial', sa.String(length=100), nullable=True),
    sa.Column('request_source', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificate_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificate_requests_common_name'), ['common_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_requests_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificate_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_certificate_requests_common_name'))

    op.drop_table('certificate_requests')
    # ### end Alembic commands ###
